url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/ressources" # the subpath of your site, e.g. /blog
title: "some notes" # the name of your site, e.g. ACME Corp.
collections:
  techno:
    output: true    
    permalink: /:path